In [1]:
import tensorflow as tf

2025-01-28 19:25:27.750444: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-28 19:25:27.760139: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1738072527.770985   26820 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1738072527.774149   26820 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-28 19:25:27.785827: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [3]:
from dynamic_convolution_layer import DynamiConvolutionLayer

In [4]:
inp=tf.random.uniform(shape=(10,256,256,3),minval=0.0,maxval=1.0)

2025-01-28 19:26:39.569685: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [5]:
inp.shape

TensorShape([10, 256, 256, 3])

In [6]:
batch_size=10
classes_config={
    0:3,
    1:4,
    2:2
}


In [7]:
conv_layer_config=[
    {
        'filters':16,
        'kernel_size':(3,3),
        'padding':"same",
        'activation':"relu",
        'kernel_initializer':"he_uniform"
    },
     {
        'filters':32,
        'kernel_size':(5,5),
        'padding':"same",
        'activation':"relu",
        'kernel_initializer':"he_uniform"
    }
    
]

In [8]:
dense_layer_config=[
    {
        'units':256,
        'activation':"relu",
        'kernel_initializer':"he_uniform"
    },
    {
        'units':32,
        'activation':"relu",
        'kernel_initializer':"he_uniform"
    }
]

In [9]:
last_layer_config={
    'activation':"softmax",
    'kernel_initializer':"glorot_uniform"
}

In [10]:
pre_dcn_layers_config={
    "ConvolutionLayers":conv_layer_config,
    "DenseLayers":dense_layer_config,
    "LastLayer":last_layer_config
}

In [12]:
pred1,pred2=DynamiConvolutionLayer(
    batch_size=batch_size,
    classes_config=classes_config,
    pre_dcn_layers_config=pre_dcn_layers_config
)(inp)

Input Config:{0: <tf.Tensor 'input_separation_layer_1/cond/Identity:0' shape=(None,) dtype=int64>, 1: <tf.Tensor 'input_separation_layer_1/cond_1/Identity:0' shape=(None,) dtype=int64>, 2: <tf.Tensor 'input_separation_layer_1/cond_2/Identity:0' shape=(None,) dtype=int64>}
Class:0
Input indexes:Tensor("input_separation_layer_1/cond/Identity:0", shape=(None,), dtype=int64)
Input to model:Tensor("cond/GatherV2:0", shape=(None, 64, 64, 32), dtype=float32)
(None, 64, 64, 32)
None
Padding length:1
Before Padding:
X:Tensor("dense_7_1/Softmax:0", shape=(None, 3), dtype=float32)
X_shape:(None, 3)
After Padding:
Y:Tensor("cond/Identity:0", shape=(None, None), dtype=float32)
Y_shape:(None, None)
Padding length:1
Before Padding:
X:Tensor("cond/hybrid__inception__skip_connection__layer_1/dense_7_1/Softmax:0", shape=(None, 3), dtype=float32)
X_shape:(None, 3)
After Padding:
Y:Tensor("cond/hybrid__inception__skip_connection__layer_1/cond/Identity:0", shape=(None, None), dtype=float32)
Y_shape:(None, 

/home/amartya/.local/lib/python3.10/site-packages/keras/src/layers/layer.py:1381: UserWarning: Layer 'input_driven_convolution_decider' looks like it has unbuilt state, but Keras is not able to trace the layer `call()` in order to build it automatically. Possible causes:
1. The `call()` method of your layer may be crashing. Try to `__call__()` the layer eagerly on some test input first to see if it works. E.g. `x = np.random.random((3, 4)); y = layer(x)`
2. If the `call()` method is correct, then you may need to implement the `def build(self, input_shape)` method on your layer. It should create all variables used by the layer (e.g. by calling `layer.build()` on all its children layers).
Exception encountered: ''[1, 0]''
  warnings.warn(
/home/amartya/.local/lib/python3.10/site-packages/keras/src/layers/layer.py:391: UserWarning: `build()` was called on layer 'input_driven_convolution_decider', however the layer does not have a `build()` method implemented and it looks like it has unbui

Before Padding:
X:Tensor("input_driven_convolution_decider_1/cond/hybrid__inception__skip_connection__layer_1/dense_7_1/Softmax:0", shape=(None, 3), dtype=float32)
X_shape:(None, 3)
After Padding:
Y:Tensor("input_driven_convolution_decider_1/cond/hybrid__inception__skip_connection__layer_1/cond/Identity:0", shape=(None, None), dtype=float32)
Y_shape:(None, None)
Input Config:{0: <tf.Tensor: shape=(0,), dtype=int64, numpy=array([], dtype=int64)>, 1: <tf.Tensor: shape=(0,), dtype=int64, numpy=array([], dtype=int64)>, 2: <tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>}
Class:2
Input indexes:[0 1 2 3 4 5 6 7 8 9]
Input to model:[[[[0.04410867 1.5748645  1.3789766  ... 0.         0.
    1.3647392 ]
   [0.5939323  1.533505   1.5938572  ... 0.16982284 0.
    1.3730043 ]
   [0.4625257  1.6020033  1.500249   ... 0.         0.18274626
    2.124932  ]
   ...
   [0.8649756  1.4948733  1.6697316  ... 0.         0.
    1.4502045 ]
   [0.36619407 1.7913041  1.615739

In [13]:
pred1

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0.21919043, 0.16356052, 0.6172491 ],
       [0.22736722, 0.30180117, 0.47083166],
       [0.21081556, 0.23014833, 0.5590361 ],
       [0.27701208, 0.26505828, 0.45792958],
       [0.22920534, 0.34915918, 0.4216355 ],
       [0.21568413, 0.25791845, 0.52639747],
       [0.20291553, 0.23071954, 0.5663649 ],
       [0.26204148, 0.26969016, 0.46826836],
       [0.23000874, 0.21958755, 0.5504038 ],
       [0.3499886 , 0.1847313 , 0.4652801 ]], dtype=float32)>

In [14]:
pred2.shape

TensorShape([10, 4])

In [15]:
pred2

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[0.51744246, 0.48255748, 0.        , 0.        ],
       [0.5       , 0.5       , 0.        , 0.        ],
       [0.5       , 0.5       , 0.        , 0.        ],
       [0.51512045, 0.48487955, 0.        , 0.        ],
       [0.507138  , 0.492862  , 0.        , 0.        ],
       [0.511952  , 0.48804802, 0.        , 0.        ],
       [0.5       , 0.5       , 0.        , 0.        ],
       [0.50463843, 0.49536157, 0.        , 0.        ],
       [0.5333347 , 0.46666533, 0.        , 0.        ],
       [0.5493458 , 0.45065418, 0.        , 0.        ]], dtype=float32)>